### ISSUE TITLE
Retry rules that Error with known messages

### ISSUE THREAD

**Issue by AleksandarSavchev** [gardener/diki#253]
**What would you like to be added**:
Rules can return Errored checkResults with with messages that suggest the error to be transient. We should retry the rule execution of rules that have errored with known to be transient error messages.

- [x] Implement `RetryableRule` wrapper struct #257 
- [x] Use `RetryableRule` for `gardener` provider #257 
- [x] Use `RetryableRule` for `virtualgarden` provider #259
- [x] Use `RetryableRule` for `managedk8s` provider #259

Command executions may error with `timeout` or `connection reset`, such errors should be reset by the `Execute()` method of `PodExecutor`

- [x] Improve `PodExecutor`'s `Execute()`  to retry timeouts and `connection reset` errors #260

**Why is this needed**:
This would help avoid transient errors.
