### ISSUE TITLE
☂ Implement `Security Hardened Kubernetes Cluster` ruleset

### ISSUE THREAD

**Issue by AleksandarSavchev** [gardener/diki#356]
**What would you like to be added**:
`DISA Kubernetes Security Technical Implementation` Guide should be extended with a new ruleset `Security Hardened Kubernetes Cluster` which aims to additionally increase the security posture of a Kubernetes cluster. Thos ruleset should be added to the `managedk8s` provider.

- [X] Add `Security Hardened Kubernetes Cluster` ruleset guide https://github.com/gardener/diki/pull/342
- [x] Add `Security Hardened Kubernetes Cluster` ruleset to `managedk8s` provider https://github.com/gardener/diki/pull/359
- [x] Implement Rules
  - [x] 2000 Ingress and egress traffic must be restricted by default. https://github.com/gardener/diki/pull/383
  - [x] 2001 Containers must be forbidden to escalate privileges. https://github.com/gardener/diki/pull/375
  - [x] 2002 Storage Classes should have a "Delete" reclaim policy. https://github.com/gardener/diki/pull/387
  - [x] 2003 Pods should use only allowed volume types. https://github.com/gardener/diki/pull/391
  - [x] 2004 Limit the Services of type NodePort. https://github.com/gardener/diki/pull/376
  - [x] 2005 Container images must come from trusted repositories. https://github.com/gardener/diki/pull/380
  - [x] 2006 Limit the use of wildcards in RBAC resources. https://github.com/gardener/diki/pull/382
  - [x] 2007 Limit the use of wildcards in RBAC verbs. https://github.com/gardener/diki/pull/389
  - [X] 2008 Pods must not be allowed to mount host directories. https://github.com/gardener/diki/pull/371
- [x] Add new usage documentation for running the `Security Hardened Kubernetes Cluster` ruleset

Ruleset documentation: https://github.com/gardener/diki/blob/main/docs/rulesets/security-hardened-k8s/ruleset.md
